version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: localhost 
      # Add other environment variables needed by the application here

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: me_challenge
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
