// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type AccountUpdates struct {
	ID          string                `json:"id"`
	AccountType string                `json:"account_type"`
	Tokens      int64                 `json:"tokens"`
	Data        pqtype.NullRawMessage `json:"data"`
	Version     sql.NullInt32         `json:"version"`
	CreatedAt   time.Time             `json:"created_at"`
}

type Accounts struct {
	ID          string                `json:"id"`
	AccountType string                `json:"account_type"`
	Tokens      int64                 `json:"tokens"`
	Data        pqtype.NullRawMessage `json:"data"`
	Version     sql.NullInt32         `json:"version"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}
